import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f6f9ff',
        'surface-dim': '#cfdbe8',
        'surface-bright': '#f6f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ebf5ff',
        'surface-container': '#e3effc',
        'surface-container-high': '#ddeaf7',
        'surface-container-highest': '#d8e4f1',
        'on-surface': '#111d26',
        'on-surface-variant': '#44474a',
        'inverse-surface': '#26323b',
        'inverse-on-surface': '#e6f2ff',
        outline: '#75777a',
        'outline-variant': '#c5c7ca',
        'surface-tint': '#5b5f62',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#181c1f',
        'on-primary-container': '#818488',
        'inverse-primary': '#c4c7cb',
        secondary: '#116c47',
        'on-secondary': '#ffffff',
        'secondary-container': '#9ef1c2',
        'on-secondary-container': '#18704b',
        'secondary-fixed': '#a1f4c5',
        'secondary-fixed-dim': '#85d7aa',
        'on-secondary-fixed': '#002112',
        'on-secondary-fixed-variant': '#005233',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f6f9ff',
        'on-background': '#111d26',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
        geist: ['Geist', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-md': '1.5rem',
        'gutter-lg': '2rem',
        margin: '1rem',
        'margin-md': '2rem',
        'margin-lg': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
      },
      boxShadow: {
        level1: '0 1px 3px 0 rgba(18, 22, 25, 0.03), 0 1px 2px -1px rgba(18, 22, 25, 0.02)',
        level2: '0 4px 12px -2px rgba(18, 22, 25, 0.06), 0 2px 6px -1px rgba(18, 22, 25, 0.03)',
        level3: '0 20px 25px -5px rgba(18, 22, 25, 0.08), 0 8px 10px -6px rgba(18, 22, 25, 0.04)',
      },
    },
  },
  plugins: [],
};

export default config;
