import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        ink: '#0f172a',
        'surface-canvas': '#f8fafc',
        surface: '#f6f9ff',
        'surface-dim': '#cfdbe8',
        'surface-bright': '#f6f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#e2e8f0',
        'surface-container-high': '#cbd5e1',
        'surface-container-highest': '#94a3b8',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#1e293b',
        'inverse-on-surface': '#f8fafc',
        outline: '#94a3b8',
        'outline-variant': '#e2e8f0',
        'surface-tint': '#5b5f62',
        primary: '#0f172a',
        'on-primary': '#ffffff',
        'primary-container': '#1e293b',
        'on-primary-container': '#f8fafc',
        'inverse-primary': '#cbd5e1',
        secondary: '#0f766e',
        'on-secondary': '#ffffff',
        'secondary-container': '#ccfbf1',
        'on-secondary-container': '#115e59',
        'secondary-fixed': '#99f6e4',
        'secondary-fixed-dim': '#5eead4',
        'on-secondary-fixed': '#042f2e',
        'on-secondary-fixed-variant': '#134e4a',
        error: '#dc2626',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#991b1b',
        background: '#f8fafc',
        'on-background': '#0f172a',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
        geist: ['Geist', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-md': '1.5rem',
        'gutter-lg': '2rem',
        margin: '1rem',
        'margin-md': '2rem',
        'margin-lg': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
      },
      boxShadow: {
        level1: '0 1px 3px 0 rgba(18, 22, 25, 0.03), 0 1px 2px -1px rgba(18, 22, 25, 0.02)',
        level2: '0 4px 12px -2px rgba(18, 22, 25, 0.06), 0 2px 6px -1px rgba(18, 22, 25, 0.03)',
        level3: '0 20px 25px -5px rgba(18, 22, 25, 0.08), 0 8px 10px -6px rgba(18, 22, 25, 0.04)',
        'elevation-1': '0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px -1px rgba(0, 0, 0, 0.06)',
        'elevation-2': '0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.06)',
        'elevation-3': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
